OPEN-ENT-NG/collaborative-wall

- frontend/package.json
- frontend/package.json.template
- frontend/src/components/description-wall/index.tsx
- frontend/src/components/note/index.tsx
- frontend/src/main.tsx
- frontend/src/services/api/index.ts
Description: 
Ajout du composant Card pour créer le composant note avec des modifications css
Ticket : 
https://edifice-community.atlassian.net/browse/WB2-236
> feat: #WB2-236, add component card to create note with modifications css

- frontend/src/components/note-modal/index.tsx
- frontend/src/components/note/index.tsx
- frontend/src/routes/collaborative-wall/index.tsx
Add note-modal components.
NoteModal is lazy loaded in routes/collaborative-wall component and added within a Suspense component. 
NoteModal is shown on Note click.
> Show Note info modal on Note click

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
- frontend/package.json
- frontend/src/config/config.ts
- frontend/src/routes/index.tsx
- frontend/src/styles/index.css
Description : 
Ajout du component explorer sur la page d'accueil de l'app 
Ticket : 
https://edifice-community.atlassian.net/browse/WB2-1311
> feat: #WB2-1311, add config to integrate explorer component

- frontend/src/components/note-modal/index.tsx
- frontend/src/config/init-config/index.ts
- frontend/src/services/api/index.ts
- frontend/src/services/queries/index.ts
- frontend/src/utils/square.tsx
Description : 
- Ajout du composant Select pour sélectionner une couleur 
- Externalisation de l'api "put" dans api/index
Ticket : https://edifice-community.atlassian.net/browse/WB2-1260
> feat: #WB2-1260, add select to change or add color to a note

- backend/src/main/resources/i18n/fr.json
- frontend/src/components/note-modal/index.tsx
- frontend/src/components/show-media-type/index.tsx
- frontend/src/components/toolbar-media/index.tsx
- frontend/src/hooks/useMediaLibrary.ts
- frontend/src/styles/index.css
Description : Ajout d'une image dans la Note => Ajout d'un hook pour gérer la MediaLibrary / Ajout d'un bouton de suppression de l'image / Ajout de l'image dans le contenu de la modal Note
Ticket : https://edifice-community.atlassian.net/browse/WB2-238
> feat: #WB2-238, add an image in note modal

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
Ce commit intègre les droits normalisés dans l'application
> [EDIFICE] feat: #WB2-1400, add normalized rights

- backend/src/main/resources/jsonschema/collaborativewallnote.json
- frontend/src/components/note-modal/index.tsx
- frontend/src/components/show-media-type/index.tsx
- frontend/src/hooks/useMediaLibrary.ts
- frontend/src/hooks/useMoveNote.ts
- frontend/src/models/noteMedia.ts
- frontend/src/models/notes.ts
Add save note media feature and show saved media in Note Modal
> Feat/wb2 11: add save note media feature

- frontend/src/components/note-modal/index.tsx
- frontend/src/components/note/index.tsx
- frontend/src/components/show-media-type/index.tsx
- frontend/src/styles/index.css
> feat: #WB2-1430, add media to vignette

- frontend/src/components/content-note/index.tsx
- frontend/src/components/show-media-type/index.tsx
- frontend/src/hooks/useMediaLibrary.ts
Description: Fix pour l'ajout des video embed dans le contenu multimedia d'une note
Ticket : https://edifice-community.atlassian.net/browse/WB2-1485
> fix: WB2-1485, fix add embed video

- frontend/src/components/note/index.tsx
- frontend/src/components/toolbar/index.tsx
- frontend/src/components/whiteboard-component/index.tsx
- frontend/src/components/whiteboard-wrapper/index.tsx
- frontend/src/features/app-actions/index.tsx
- frontend/src/features/history/hooks/useHistory.ts
- frontend/src/hooks/useAccess.ts
- Check if rights are managed correctly.
> fix: #WB2-1257, check rights

- frontend/src/components/content-note/index.tsx
- frontend/src/components/create-note-modal/index.tsx
- frontend/src/components/update-note-modal/index.tsx
- frontend/src/features/note-actions/index.tsx
- frontend/src/routes/collaborative-wall/index.tsx
Save editor content in Update Note and Create Note Modals.
I may merge Update Note and Create Note modals in a future PR.
> feat: #WB2-11, save editor content in Note edition mode

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/helpers/NotesHelper.java
- frontend/src/components/update-note-modal/index.tsx
- frontend/src/features/history/hooks/useHistory.ts
- frontend/src/hooks/useEditNote.ts
Return updated Note in backend API Response instead of wall and adapt frontend API response handling
> fix: #WB2-1552, return updated Note in backend API Response instead of wall and adapt frontend API response handling

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
add backend route for GET /id/note/idNote to render react app
> fix: #WB2-1568, add backend route for GET /id/note/idNote to render react app

- frontend/src/components/toolbar/index.tsx
Add Undo/Redo keyboard shortcuts with `useHotkeys` hook.
> feat: #WB2-1584, add Undo/Redo keyboard shortcuts

- backend/src/main/resources/i18n/fr.json
- frontend/src/features/note-modal/components/NoteContent.tsx
- frontend/src/styles/index.css
Add Note Modal Editor placeholder
Related to https://github.com/edificeio/edifice-ui/pull/136
> feat: #WB2-1590, add Note Modal Editor placeholder

- frontend/src/components/note/index.tsx
Add onClick on Note component (through Card component) for users that are readers only to be able to view the Note modal
> fix: #WB2-1572, add Note onClick for readers

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
- backend/src/main/java/net/atos/entng/collaborativewall/controllers/helpers/NotesHelper.java
> feat: #WB2-1473, add Note creation event

- frontend/src/features/collaborative-wall/components/custom-background.tsx
- frontend/src/features/note-modal/hooks/use-note-modal.ts
- frontend/src/store/whiteboard/store.ts
- frontend/src/store/whiteboard/types.ts
Description : 
Ajout de positions aléatoires lorsque l'on crée une note afin qu'elle ne puisse pas ce superposer si l'on crée plusieurs notes à la suite sans les déplacer. 
Ticket : https://edifice-community.atlassian.net/browse/WB2-1632
> feat: WB2-1632, add random position when create a note

- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
Add print route for Library pdf publishing
> fix: #WB2-1638, add print route

- backend/deployment/collaborativewall/conf.json.template
- backend/gradle.properties
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/features/App/AppHeader.tsx
See [PR](https://github.com/edificeio/edifice-ui/pull/187)
>
>
>
> feat(ui): #WB2-1742, add shareOptions to make ShareModal compatible with any apps

- backend/deployment/collaborativewall/migration/2.0.0/migrateWallReadRights.js
Ajout du script de migration des droits read pour les notes.
>
>
> fix: #WB2-1819, add migrate wall read rights script

- frontend/src/features/Wall/Wall.tsx
- frontend/src/hooks/useCustomReactFlow.ts
- frontend/src/routes/index.tsx
- frontend/src/routes/note-modal/index.tsx
- frontend/src/routes/page-error/index.tsx
- frontend/src/services/api/index.ts
- frontend/src/utils/checkQueryResult.ts
Cette PR check si les réponses http retourne une erreur lié à un changement de droit (401) ou une suppression (404). Il redirige vers une page d'erreur si il détecte l'une de ces erreurs (par exemple un droit m'a été supprimé pendant que je crée une note).
Les websockets aussi détecteront ce changement car lorsque des update sont réalisés il y a des invalidate query puis refetch...
>
- [ X] Bug fix (PATCH)
>
>
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have …
> fix: #WB2-1711, manage api errors

- backend/src/main/resources/i18n/fr.json
- frontend/src/features/Note/components/NoteContent.tsx
Ajout d'un switch pour afficher le composant qui permet d'ajouter un contenu à une note.
>
>
>
> feat: #WB2-2532, add switch to show add content in notes

- backend/pom.xml
- backend/src/main/java/net/atos/entng/collaborativewall/CollaborativeWall.java
- backend/src/main/java/net/atos/entng/collaborativewall/listeners/ResourceBrokerListenerImpl.java
Ce commit ajoute:
- un listener sur le broker pour récupérer les info concernant une ressource
- un listener permettant de partager/départager une ressource dans mur collab
>
>
>
> Feat: #pedago-2699, link into community

- backend/src/main/java/net/atos/entng/collaborativewall/CollaborativeWall.java
- backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
- backend/src/main/java/net/atos/entng/collaborativewall/explorer/WallExplorerPlugin.java
- backend/src/main/java/net/atos/entng/collaborativewall/service/impl/MongoDbCollaborativeWallService.java
Ce commit publie les event de suppression des mur sur le broker
>
>
>
> feat: #PEDAGO-3019, notify deleted resources on broker

- frontend/src/config/explorer.ts
Change workflow permission for copy action
> fix: change-copy-workflow-permission
